
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          # - not_null
          # - accepted_values:
              # values: [1, 2]
              # quote: false

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          # - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: snowflake_customer_purchases
    description: "Total Purchases To Each Customer"
    columns:
      - name: c_custkey
        description: "Customer Key Number"
        tests:
          - unique
          - not_null
        
  - name: cumulative_orders_by_date
    description: "Total Cumulative Orders By Date"
    columns:
      - name: o_orderdate
        description: "order_date"
        # tests:
        #   - unique
        #   - not_null

  - name: playing_with_tests
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']

sources:
  - name: sample
    database: snowflake_sample_data  # Tell dbt to look for the source in the "raw" database
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders
